PROPERTY_TYPE_OPTIONS = ["Недвижимость", "Автомобиль"]

REALTY_TYPE_OPTIONS = ["Квартира", "Дом"]
MATERIAL_OPTIONS = [
    "Панельный",
    "Монолитный",
    "Кирпичный",
    "Блочный",
    "Деревянный",
    "Другое",
]

BRAND_OPTIONS = [
    "LADA (ВАЗ)",
    "Toyota",
    "Nissan",
    "Hyundai",
    "Kia",
    "Volkswagen",
    "Mercedes-Benz",
    "BMW",
    "Chevrolet",
    "Ford",
    "Renault",
    "Opel",
    "Mitsubishi",
    "Audi",
    "Mazda",
    "Skoda",
    "Honda",
    "УАЗ",
    "Daewoo",
    "ГАЗ",
    "Peugeot",
    "Lexus",
    "Land Rover",
    "Volvo",
    "Subaru",
    "Chery",
    "Citroen",
    "Suzuki",
    "Lifan",
    "SsangYong",
    "Infiniti",
    "Geely",
    "Porsche",
    "ЗАЗ",
    "Datsun",
    "Fiat",
    "Great Wall",
    "Jeep",
    "Dodge",
    "Москвич",
    "Chrysler",
    "Jaguar",
    "ИЖ",
    "Cadillac",
    "MINI",
    "Vortex",
    "Daihatsu",
    "ЛуАЗ",
    "Ravon",
    "Saab",
    "Другое",
]
MODEL_OPTIONS_BY_BRAND = {
    "AC": ["Cobra"],
    "AMC": ["Eagle"],
    "Acura": [
        "MDX",
        "EL",
        "TL",
        "RL",
        "RSX",
        "TLX",
        "RDX",
        "Legend",
        "TSX",
        "ILX",
        "ZDX",
    ],
    "Adler": ["Diplomat", "Trumpf Junior"],
    "Alfa Romeo": [
        "Giulietta",
        "146",
        "159",
        "GT",
        "156",
        "Brera",
        "164",
        "Giulia",
        "166",
        "MiTo",
        "147",
        "Spider",
        "145",
        "90",
        "GTV",
        "Stelvio",
        "33",
        "8C Competizione",
    ],
    "Alpina": ["B3", "D3", "B7", "B6", "B10"],
    "Ariel": ["Atom"],
    "Aro": ["24 аро", "10"],
    "Asia": ["Topic", "Rocsta"],
    "Aston Martin": [
        "Rapide",
        "Vanquish",
        "DB9",
        "V12 Vantage",
        "DBS",
        "V8 Vantage",
        "DB7",
        "DBX",
        "Virage",
    ],
    "Auburn": ["Speedster"],
    "Audi": [
        "A6",
        "100",
        "A3",
        "80",
        "A4",
        "Q3",
        "A5",
        "A8",
        "A6 allroad",
        "S3",
        "Q7",
        "Q5",
        "TT",
        "S8",
        "A7",
        "Q8",
        "R8",
        "200",
        "A1",
        "A4 allroad",
        "RS 6",
        "RS Q3",
        "RS 5",
        "S4",
        "A2",
        "S5",
        "e-tron",
        "S6",
        "SQ5",
        "V8",
        "Coupe",
        "RS 3",
        "90",
        "Q3 Sportback",
        "SQ8",
        "Q2",
        "RS 7",
        "RS 4",
        "e-tron S Sportback",
        "TTS",
        "S7",
        "TT RS",
        "S2",
        "SQ7",
        "920",
    ],
    "Austin": ["Montego", "Mini"],
    "BAIC": ["EU5"],
    "BMW": [
        "3 серии",
        "5 серии",
        "i3",
        "X5",
        "X6",
        "X5 M",
        "X3",
        "6 серии",
        "7 серии",
        "1 серии",
        "X1",
        "4 серии",
        "X7",
        "X4",
        "M2",
        "X6 M",
        "M3",
        "X2",
        "8 серии",
        "Z3",
        "M5",
        "M4",
        "340",
        "2 серии Active Tourer",
        "2 серии",
        "i8",
        "Z4",
        "2 серии Gran Tourer",
        "M6",
        "321",
        "326",
        "Z3 M",
        "02 (E10)",
        "Z1",
        "2000 C/CS",
        "600",
        "X4 M",
        "Z8",
    ],
    "BYD": ["S6", "F3", "E6", "Flyer", "Song EV"],
    "Bentley": [
        "Flying Spur",
        "Mulsanne",
        "Brooklands",
        "Continental GT",
        "Bentayga",
        "Arnage",
        "Continental Flying Spur",
        "Continental",
        "Azure",
        "Turbo R",
    ],
    "Borgward": ["2000"],
    "Brabus": ["SV12"],
    "Brilliance": ["V3", "H530", "M2 (BS4)", "H230", "V5", "M1 (BS6)"],
    "Bugatti": ["Type 55"],
    "Buick": [
        "Rendezvous",
        "Riviera",
        "Encore",
        "LaCrosse",
        "Special",
        "Regal",
        "Skylark",
        "Envision",
        "Enclave",
        "LeSabre",
        "Century",
        "Park Avenue",
    ],
    "CHERYEXEED": ["TXL"],
    "Cadillac": [
        "SRX",
        "CTS",
        "Escalade",
        "XT6",
        "ELR",
        "BLS",
        "ATS",
        "Seville",
        "DeVille",
        "CT6",
        "CTS-V",
        "XT4",
        "Eldorado",
        "STS",
        "XT5",
        "Fleetwood",
        "Brougham",
        "XTS",
    ],
    "Chana": ["Benni"],
    "ChangFeng": ["Flying"],
    "Changan": ["CS35", "Eado", "CS35PLUS", "CS75", "Benni", "CS55"],
    "Changhe": ["Ideal"],
    "Chery": [
        "QQ6 (S21)",
        "Tiggo (T11)",
        "IndiS (S18D)",
        "Bonus (A13)",
        "Amulet (A15)",
        "Tiggo 5",
        "CrossEastar (B14)",
        "Tiggo 7",
        "M11 (A3)",
        "Fora (A21)",
        "Bonus 3 (E3/A19)",
        "Tiggo 4",
        "Kimo (A1)",
        "Tiggo 8",
        "Sweet (QQ)",
        "Tiggo 2",
        "Tiggo 7 Pro",
        "Very (A13)",
        "Tiggo 3",
        "Oriental Son (B11)",
        "Arrizo 7",
        "Karry",
        "E5",
    ],
    "Chevrolet": [
        "Aveo",
        "Lacetti",
        "Niva",
        "Lanos",
        "Cruze",
        "Tracker",
        "Orlando",
        "Equinox",
        "TrailBlazer",
        "Tahoe",
        "Epica",
        "Captiva",
        "Viva",
        "Spark",
        "Cobalt",
        "Evanda",
        "Bolt",
        "Camaro",
        "Rezzo",
        "Lumina",
        "Volt",
        "Malibu",
        "Blazer",
        "Express",
        "Traverse",
        "Lumina APV",
        "Van",
        "Corvette",
        "Metro",
        "Tacuma",
        "Silverado",
        "Nexia",
        "Astro",
        "Suburban",
        "Avalanche",
        "Cruze (HR)",
        "Bel Air",
        "El Camino",
        "Prizm",
        "Cavalier",
        "Caprice",
        "Impala",
        "HHR",
        "C-10",
        "Blazer K5",
        "SS",
        "Deluxe",
        "Master",
        "Alero",
        "Corsica",
        "S-10 Pickup",
        "Monte Carlo",
        "Starcraft",
        "MW",
        "Venture",
    ],
    "Chrysler": [
        "PT Cruiser",
        "300C",
        "Voyager",
        "Town & Country",
        "Pacifica",
        "Neon",
        "Concorde",
        "Vision",
        "Sebring",
        "200",
        "LeBaron",
        "300M",
        "Fifth Avenue",
        "Crossfire",
        "Stratus",
        "Cirrus",
        "Cordoba",
        "Imperial",
        "Intrepid",
        "LHS",
        "New Yorker",
        "Saratoga",
        "Imperial Crown",
    ],
    "Citroen": [
        "C4",
        "C3",
        "Berlingo",
        "C4 Picasso",
        "Xsara Picasso",
        "C3 Picasso",
        "C5",
        "Jumpy",
        "C-Elysee",
        "DS",
        "DS4",
        "C4 Aircross",
        "DS3",
        "C-Crosser",
        "BX",
        "Xantia",
        "C5 Aircross",
        "Xsara",
        "C2",
        "DS5",
        "C8",
        "SpaceTourer",
        "C1",
        "C3 Aircross",
        "Evasion",
        "XM",
        "GS",
        "C6",
        "Saxo",
        "C4 Cactus",
        "Visa",
        "Nemo",
    ],
    "DKW": ["3=6"],
    "DS": ["7 Crossback", "4"],
    "DW Hower": ["H3", "H5"],
    "Dacia": ["Duster", "Solenza", "Logan", "Lodgy", "SuperNova", "1310", "Sandero"],
    "Dadi": ["City Leading", "Smoothing"],
    "Daewoo": [
        "Nubira",
        "Nexia",
        "Matiz",
        "Gentra",
        "Lanos",
        "Sens",
        "Tico",
        "Espero",
        "Leganza",
        "Prince",
        "Winstorm",
        "Racer",
        "Magnus",
        "Kalos",
        "Damas",
        "Lacetti Premiere",
        "Matiz Creative",
        "Tacuma",
        "Lacetti",
        "Rezzo",
    ],
    "Daihatsu": [
        "Copen",
        "Pyzar",
        "Move",
        "YRV",
        "Terios",
        "Mira",
        "Hijet",
        "Charade",
        "Storia",
        "Mira e:S",
        "Boon",
        "Boon Luminas",
        "Move Conte",
        "Sirion",
        "Delta Wagon",
        "Tanto",
        "Applause",
        "Extol",
        "Be-go",
        "Rocky",
        "Atrai",
        "MAX",
        "Rugger",
        "Coo",
        "Esse",
        "Cuore",
        "Feroza",
        "Opti",
        "Leeza",
    ],
    "Daimler": ["X350", "DS420"],
    "Datsun": ["on-DO", "mi-DO", "Violet", "Bluebird", "Laurel", "Sunny"],
    "Delage": ["D6"],
    "Derways": ["Aurora", "Plutus", "Shuttle", "Cowboy", "Saladin"],
    "Dodge": [
        "Charger",
        "Stratus",
        "Caliber",
        "Avenger",
        "RAM",
        "Caravan",
        "Journey",
        "Durango",
        "Neon",
        "Intrepid",
        "Nitro",
        "Challenger",
        "Dakota",
        "Stealth",
        "Aries",
        "Dart",
        "Shadow",
        "Daytona",
        "Magnum",
        "Viper",
        "WC series",
        "Dynasty",
        "Spirit",
    ],
    "DongFeng": ["H30 Cross", "S30", "AX7", "MPV"],
    "Doninvest": ["Kondor", "Assol", "Orion"],
    "Eagle": ["Vision", "Talon"],
    "Excalibur": ["Series V"],
    "FAW": [
        "Besturn B50",
        "V5",
        "Vita",
        "Besturn X40",
        "Besturn X80",
        "Oley",
        "Jinn",
        "D60",
    ],
    "FSO": ["125p"],
    "Ferrari": [
        "458",
        "488",
        "360",
        "F430",
        "812",
        "California",
        "F12berlinetta",
        "599",
        "612",
        "FF",
        "GTC4Lusso",
    ],
    "Fiat": [
        "Albea",
        "508",
        "Ulysse",
        "Doblo",
        "Tipo",
        "124 Spider",
        "Bravo",
        "Panda",
        "Brava",
        "Coupe",
        "Uno",
        "Punto",
        "Croma",
        "Tempra",
        "Linea",
        "Palio",
        "Stilo",
        "500",
        "Marea",
        "Multipla",
        "Fiorino",
        "Regata",
        "Sedici",
        "Scudo",
        "Fullback",
        "127",
        "Freemont",
        "Idea",
        "Seicento",
        "Siena",
        "500L",
        "500X",
    ],
    "Fisker": ["Karma"],
    "Ford": [
        "Focus",
        "Explorer",
        "Sierra",
        "Mondeo",
        "Fusion",
        "Laser",
        "Galaxy",
        "Fiesta",
        "S-MAX",
        "Orion",
        "EcoSport",
        "C-MAX",
        "Ixion",
        "Kuga",
        "Fusion (North America)",
        "Escort",
        "Scorpio",
        "Mustang",
        "Ranger",
        "Escape",
        "Windstar",
        "Tourneo Connect",
        "F-150",
        "KA",
        "Expedition",
        "Taunus",
        "Maverick",
        "Spectron",
        "Edge",
        "Transit Connect",
        "V8",
        "Taurus",
        "Model T",
        "Focus (North America)",
        "Focus ST",
        "Granada",
        "Custom",
        "Tourneo Custom",
        "Telstar",
        "Excursion",
        "Freda",
        "Festiva",
        "Fairmont",
        "Cougar",
        "Contour",
        "Econoline",
        "Ranger (North America)",
        "Bronco-II",
        "Probe",
        "Flex",
        "Thunderbird",
        "Explorer Sport Trac",
        "Bronco",
        "Puma",
        "Mondeo ST",
        "Fiesta ST",
        "Zephyr",
        "Ranchero",
        "Crown Victoria",
        "Model A",
        "Escort (North America)",
        "Aerostar",
        "Focus RS",
        "Mainline",
        "Tourneo Courier",
        "Mustang Mach-E",
        "B-MAX",
        "Capri",
        "Tempo",
    ],
    "Foton": ["Sauvana", "Tunland"],
    "GAC": ["GS5"],
    "GMC": [
        "Jimmy",
        "Savana",
        "Canyon",
        "Sierra",
        "Yukon",
        "Suburban",
        "Terrain",
        "Envoy",
        "Acadia",
        "Safari",
        "Vandura",
    ],
    "Geely": [
        "GC6",
        "Emgrand 7",
        "MK Cross",
        "MK",
        "Emgrand EC7",
        "CK (Otaka)",
        "Emgrand X7",
        "FC (Vision)",
        "Atlas",
        "Emgrand GT",
        "SC7",
        "Coolray",
        "Haoqing",
        "Emgrand EC8",
    ],
    "Genesis": ["G80", "G90", "G70", "GV80"],
    "Geo": ["Metro", "Storm", "Prizm"],
    "Great Wall": [
        "Safe",
        "Wingle",
        "Hover M4",
        "Hover H3",
        "Hover",
        "Hover H5",
        "Deer",
        "Hover H6",
        "Wingle 7",
        "Sailor",
        "Hover M2",
        "Pegasus",
        "Peri",
        "Cowry (V80)",
        "Hover Pi",
        "Florid",
    ],
    "Hafei": ["Brio", "Simbo", "Princip"],
    "Haima": ["3", "M3", "7"],
    "Hanomag": ["Rekord"],
    "Haval": ["F7", "H5", "H6", "F7x", "H9", "H2", "H6 Coupe"],
    "Hawtai": ["Boliger", "Laville"],
    "Heinkel": ["Typ 154"],
    "Honda": [
        "Mobilio",
        "Accord",
        "CR-V",
        "Civic",
        "Civic Ferio",
        "Partner",
        "Elysion",
        "Saber",
        "Airwave",
        "Fit",
        "Integra",
        "Odyssey",
        "HR-V",
        "Freed",
        "Stepwgn",
        "Stream",
        "Orthia",
        "Shuttle",
        "Capa",
        "Vezel",
        "Inspire",
        "Jade",
        "Jazz",
        "Legend",
        "Ridgeline",
        "Logo",
        "Insight",
        "Rafaga",
        "Civic Type R",
        "Grace",
        "Vamos",
        "Avancier",
        "Ascot",
        "Torneo",
        "Prelude",
        "Element",
        "Pilot",
        "Odyssey (North America)",
        "S-MX",
        "Fit Shuttle",
        "Domani",
        "Ascot Innova",
        "Crosstour",
        "Fit Aria",
        "Mobilio Spike",
        "CR-Z",
        "City",
        "N-One",
        "N-BOX",
        "Vigor",
        "Crossroad",
        "Edix",
        "FR-V",
        "MDX",
        "Life",
        "CR-X",
        "Acty",
        "Integra SJ",
        "N-WGN",
        "Concerto",
        "Z",
        "Beat",
        "S2000",
        "Today",
        "Passport",
        "NSX",
        "N-BOX Slash",
        "Zest",
        "That'S",
        "FCX Clarity",
        "S660",
    ],
    "HuangHai": ["Antelope"],
    "Hudson": ["Deluxe Eight"],
    "Hummer": ["H2", "H3", "H1"],
    "Hyundai": [
        "ix35",
        "Starex",
        "Matrix",
        "Santa Fe",
        "Creta",
        "Elantra",
        "Accent",
        "Solaris",
        "i40",
        "Grace",
        "Tucson",
        "i30",
        "Getz",
        "Sonata",
        "Grand Starex",
        "Genesis",
        "Terracan",
        "H-1",
        "Galloper",
        "Avante",
        "Lantra",
        "Grandeur",
        "Equus",
        "Veracruz",
        "H200",
        "Trajet",
        "Genesis Coupe",
        "i30 N",
        "Coupe",
        "Verna",
        "ix55",
        "Veloster",
        "i20",
        "XG",
        "Tiburon",
        "i10",
        "Pony",
        "Excel",
        "Scoupe",
        "IONIQ",
        "Tuscani",
        "Atos",
        "Santamo",
        "Lavita",
        "Palisade",
        "Kona",
        "Dynasty",
        "Click",
        "Marcia",
    ],
    "IVECO": ["Massif"],
    "Infiniti": [
        "FX",
        "M",
        "QX70",
        "QX56",
        "QX4",
        "QX60",
        "QX80",
        "EX",
        "Q50",
        "Q60",
        "G",
        "QX50",
        "Q70",
        "JX",
        "QX30",
        "Q",
        "Q30",
        "I",
    ],
    "Iran Khodro": ["Samand"],
    "Isuzu": [
        "Rodeo",
        "Gemini",
        "Bighorn",
        "Trooper",
        "Axiom",
        "VehiCross",
        "Wizard",
        "D-Max",
        "Amigo",
        "Aska",
        "Fargo Filly",
        "MU",
        "Fargo",
    ],
    "JAC": ["S1 (Rein)", "M1 (Refine)", "S5 (Eagle)", "S3", "J7", "iEV7S"],
    "JMC": ["Baodian"],
    "Jaguar": [
        "XKR",
        "XF",
        "S-Type",
        "F-Pace",
        "X-Type",
        "XJ",
        "E-Pace",
        "XE",
        "XK",
        "I-Pace",
        "F-Type",
        "XFR",
        "XJS",
        "E-type",
        "XJR",
    ],
    "Jeep": [
        "Compass",
        "Grand Cherokee",
        "Cherokee",
        "Wrangler",
        "Commander",
        "Liberty (Patriot)",
        "Liberty (North America)",
        "Renegade",
    ],
    "Jinbei": ["Haise"],
    "Kia": [
        "Cerato",
        "Sportage",
        "Optima",
        "Rio",
        "Sorento",
        "Ceed",
        "Picanto",
        "Spectra",
        "Soul",
        "Venga",
        "Carnival",
        "Shuma",
        "Carens",
        "K900",
        "Opirus",
        "Seltos",
        "Quoris",
        "Stinger",
        "Avella",
        "Mohave",
        "Magentis",
        "K5",
        "Ceed GT",
        "Sephia",
        "Clarus",
        "Retona",
        "Pregio",
        "Forte",
        "Pride",
        "XCeed",
        "Ray",
        "Joice",
        "Proceed",
        "Niro",
        "Soul EV",
        "Sedona",
        "Morning",
        "X-Trek",
    ],
    "LADA (ВАЗ)": [
        "2107",
        "2115",
        "Largus",
        "Priora",
        "Granta",
        "2114",
        "Vesta",
        "Kalina",
        "2131 (4x4)",
        "2109",
        "2105",
        "2110",
        "2101",
        "2112",
        "2121 (4x4)",
        "1111 Ока",
        "2108",
        "21099",
        "2106",
        "2104",
        "2113",
        "Niva",
        "2111",
        "2102",
        "XRAY",
        "2103",
        "2329",
        "2120 Надежда",
        "2129",
        "2123",
        "EL Lada",
    ],
    "LTI": ["TX"],
    "Lamborghini": ["Murcielago", "Huracán", "Urus", "Aventador", "Gallardo"],
    "Lancia": [
        "Kappa",
        "Lybra",
        "Dedra",
        "Thesis",
        "Delta",
        "Prisma",
        "Thema",
        "Ypsilon",
        "Phedra",
    ],
    "Land Rover": [
        "Range Rover",
        "Discovery Sport",
        "Range Rover Evoque",
        "Range Rover Sport",
        "Discovery",
        "Freelander",
        "Range Rover Velar",
        "Defender",
    ],
    "Landwind": ["X6"],
    "Lexus": [
        "ES",
        "IS",
        "RX",
        "LX",
        "NX",
        "LS",
        "GX",
        "LC",
        "GS",
        "SC",
        "CT",
        "HS",
        "UX",
        "LM",
        "RC",
        "GS F",
        "IS F",
        "RC F",
    ],
    "Lifan": [
        "Solano",
        "X60",
        "X50",
        "Myway",
        "Smily",
        "Breez (520)",
        "X70",
        "Cebrium (720)",
        "Murman (820)",
        "Celliya (530)",
    ],
    "Ligier": ["JS 51"],
    "Lincoln": [
        "Navigator",
        "Town Car",
        "Mark LT",
        "MKZ",
        "MKS",
        "MKC",
        "Continental",
        "LS",
        "MKT",
        "MKX",
        "Zephyr",
        "Mark VII",
        "Nautilus",
        "Aviator",
        "Mark VIII",
    ],
    "Lotus": ["Europa S"],
    "Luxgen": ["Luxgen7 SUV", "U7 Turbo"],
    "MG": ["F", "ZT", "ZS", "TF", "550", "6", "350", "ZR", "MGA"],
    "MINI": ["Hatch", "Countryman", "Clubman", "Cabrio", "Coupe", "Paceman"],
    "Mahindra": ["Marshal", "Bolero"],
    "Marussia": ["B1"],
    "Maruti": ["Alto"],
    "Maserati": ["Quattroporte", "Levante", "GranTurismo", "Ghibli", "4200 GT"],
    "Maybach": ["57", "62"],
    "Mazda": [
        "3",
        "6",
        "Capella",
        "CX-5",
        "Xedos 6",
        "Verisa",
        "Bongo Friendee",
        "Familia",
        "626",
        "CX-7",
        "Bongo",
        "323",
        "Premacy",
        "CX-9",
        "Atenza",
        "Demio",
        "B-series",
        "Xedos 9",
        "Biante",
        "BT-50",
        "Tribute",
        "CX-3",
        "MPV",
        "Axela",
        "Efini MS-8",
        "RX-8",
        "Millenia",
        "Protege",
        "121",
        "5",
        "2",
        "MX-3",
        "3 MPS",
        "6 MPS",
        "Revue",
        "Proceed",
        "Luce",
        "929",
        "AZ-Offroad",
        "MX-5",
        "Lantis",
        "AZ-Wagon",
        "Proceed Marvie",
        "Autozam AZ-3",
        "Flair",
        "Cronos",
        "Efini MS-6",
        "Proceed Levante",
        "Eunos 800",
        "Navajo",
        "RX-7",
        "Carol",
        "CX-8",
        "MX-6",
        "Efini MS-9",
        "Scrum",
        "Eunos 500",
        "616",
        "Persona",
        "Eunos 300",
    ],
    "McLaren": ["720S", "F1", "600LT"],
    "Mercedes-Benz": [
        "M-Класс",
        "GLA",
        "B-Класс",
        "CLS",
        "GL-Класс",
        "C-Класс",
        "S-Класс",
        "E-Класс",
        "SLK-Класс",
        "190 (W201)",
        "GL-Класс AMG",
        "Vito",
        "GLC Coupe",
        "GLE Coupe AMG",
        "V-Класс",
        "GLC",
        "GLS",
        "GLE",
        "GLK-Класс",
        "CLK-Класс",
        "CL-Класс AMG",
        "Viano",
        "W123",
        "E-Класс AMG",
        "GLE Coupe",
        "CLA",
        "A-Класс",
        "C-Класс AMG",
        "CL-Класс",
        "AMG GT",
        "G-Класс",
        "G-Класс AMG",
        "M-Класс AMG",
        "S-Класс AMG",
        "A-Класс AMG",
        "W124",
        "Vaneo",
        "R-Класс",
        "SL-Класс AMG",
        "GLS AMG",
        "CLA AMG",
        "W186",
        "X-Класс",
        "Maybach GLS",
        "GLC AMG",
        "SL-Класс",
        "CLC-Класс",
        "GLB",
        "GLC Coupe AMG",
        "GLE AMG",
        "W111",
        "CLK-Класс AMG",
        "Maybach S-Класс",
        "190 SL",
        "EQC",
        "SLC AMG",
        "CLS AMG",
        "GLA AMG",
        "W136",
        "W128",
        "SLS AMG",
        "W121",
        "SLR McLaren",
        "W108",
        "SLK-Класс AMG",
        "W115",
        "Citan",
        "W29",
        "SLC",
        "W188",
        "220 (W187)",
        "Metris",
        "W114",
        "W110",
    ],
    "Mercury": [
        "Mountaineer",
        "Grand Marquis",
        "Mystique",
        "Mariner",
        "Topaz",
        "Sable",
        "Cougar",
        "Villager",
        "Marquis",
        "Eight",
        "Monterey",
    ],
    "Metrocab": ["Metrocab I"],
    "Mitsubishi": [
        "ASX",
        "Galant",
        "Lancer",
        "Pajero",
        "Pajero Mini",
        "Pajero Sport",
        "Outlander",
        "Airtrek",
        "L200",
        "Colt",
        "L300",
        "Space Gear",
        "Eclipse",
        "Eclipse Cross",
        "Dingo",
        "Carisma",
        "Libero",
        "Minica",
        "RVR",
        "Montero Sport",
        "Montero",
        "Pajero Pinin",
        "Minicab",
        "Delica",
        "Diamante",
        "Lancer Evolution",
        "Grandis",
        "GTO",
        "Mirage",
        "Dion",
        "Space Star",
        "Chariot",
        "Space Wagon",
        "eK Wagon",
        "Pajero iO",
        "Legnum",
        "Eterna",
        "Delica D:3",
        "L400",
        "3000 GT",
        "Challenger",
        "Pajero Junior",
        "Delica D:5",
        "Toppo",
        "Jeep J",
        "FTO",
        "i",
        "Emeraude",
        "Sigma",
        "Aspire",
        "Space Runner",
        "i-MiEV",
        "Debonair",
        "eK Custom",
        "Endeavor",
        "Lancer Ralliart",
        "Delica D:2",
        "eK Space",
        "eK Sport",
        "Lancer Cargo",
        "Galant Fortis",
        "eK Classic",
        "Strada",
    ],
    "Mitsuoka": ["Le-Seyde", "Galue", "Viewt"],
    "Nissan": [
        "Wingroad",
        "Qashqai+2",
        "Note",
        "Qashqai",
        "Almera Classic",
        "Almera",
        "Micra",
        "Pathfinder",
        "X-Trail",
        "Teana",
        "March",
        "Cefiro",
        "Juke",
        "Terrano",
        "Sunny",
        "Tiida",
        "Cube",
        "Murano",
        "Maxima",
        "Laurel",
        "Expert",
        "Presage",
        "Tino",
        "Skyline",
        "AD",
        "Primera",
        "Serena",
        "Presea",
        "Datsun",
        "Fuga",
        "Patrol",
        "Pulsar",
        "Leaf",
        "Largo",
        "Bluebird",
        "Bluebird Sylphy",
        "Cedric",
        "NV200",
        "Terrano Regulus",
        "Avenir",
        "Elgrand",
        "Altima",
        "Liberty",
        "Juke Nismo",
        "Quest",
        "Safari",
        "Gloria",
        "R'nessa",
        "Armada",
        "Sentra",
        "NP300",
        "Navara (Frontier)",
        "NV100 Clipper",
        "Dayz",
        "Vanette",
        "Primastar",
        "Fairlady Z",
        "Urvan",
        "Titan",
        "Almera Tino",
        "Stagea",
        "Prairie",
        "Caravan",
        "Dualis",
        "Dayz Roox",
        "Cima",
        "Leopard",
        "350Z",
        "Lucino",
        "Bassara",
        "Otti",
        "Silvia",
        "Lafesta",
        "Latio",
        "Mistral",
        "NV350 Caravan",
        "Xterra",
        "Pino",
        "Kix",
        "Rasheen",
        "Moco",
        "GT-R",
        "Rogue",
        "Cherry",
        "100NX",
        "Roox",
        "Langley",
        "Versa",
        "Exa",
        "President",
        "200SX",
        "Homy",
        "Liberta Villa",
        "Clipper Rio",
        "300ZX",
        "Figaro",
        "280ZX",
        "Stanza",
        "NV300",
        "Bluebird Maxima",
        "370Z",
    ],
    "Oldsmobile": [
        "Eighty-Eight",
        "Silhouette",
        "Cutlass Ciera",
        "Cutlass Supreme",
        "Aurora",
    ],
    "Opel": [
        "Mokka",
        "Astra",
        "Omega",
        "Antara",
        "Corsa",
        "Insignia",
        "Kadett",
        "Zafira",
        "Frontera",
        "Vectra",
        "Monterey",
        "Agila",
        "Vivaro",
        "Meriva",
        "Combo",
        "Calibra",
        "Rekord",
        "Insignia OPC",
        "Astra OPC",
        "Ascona",
        "Vita",
        "Tigra",
        "Corsa OPC",
        "Sintra",
        "Meriva OPC",
        "Olympia",
        "Senator",
        "Zafira Life",
        "Campo",
        "Diplomat",
        "Signum",
        "P4",
        "Vectra OPC",
        "Admiral",
        "Super Six",
        "GT",
        "Kapitan",
        "Commodore",
        "Monza",
    ],
    "PUCH": ["Pinzgauer"],
    "Packard": ["Clipper"],
    "Peugeot": [
        "607",
        "406",
        "206",
        "3008",
        "408",
        "307",
        "207",
        "107",
        "308",
        "Partner",
        "407",
        "405",
        "508",
        "RCZ",
        "Expert",
        "2008",
        "4007",
        "605",
        "Bipper",
        "Traveller",
        "5008",
        "301",
        "208",
        "4008",
        "807",
        "306",
        "806",
        "309",
        "106",
        "505",
        "1007",
        "208 GTi",
        "305",
        "504",
    ],
    "Plymouth": [
        "Neon",
        "Voyager",
        "Reliant",
        "Acclaim",
        "Prowler",
        "Satellite",
        "Breeze",
    ],
    "Pontiac": [
        "Vibe",
        "Trans Sport",
        "Grand AM",
        "Bonneville",
        "Firebird",
        "Sunfire",
        "Montana",
        "Sunbird",
        "Grand Prix",
        "Aztek",
        "Solstice",
        "Parisienne",
        "Fiero",
    ],
    "Porsche": [
        "Cayenne",
        "Boxster",
        "Panamera",
        "Macan",
        "356",
        "Cayenne Coupe",
        "928",
        "911",
        "Cayman GT4",
        "Cayman",
        "924",
        "944",
        "Taycan",
        "911 GT2",
        "911 GT3",
    ],
    "Proton": ["Persona", "Putra"],
    "RAM": ["1500"],
    "Ravon": ["R2", "Nexia R3", "Gentra", "R4", "Matiz"],
    "Renaissance": ["Tropica Roadster"],
    "Renault": [
        "Logan",
        "Megane",
        "Duster",
        "Kaptur",
        "9",
        "Koleos",
        "Scenic",
        "Sandero",
        "Fluence",
        "Kangoo",
        "Symbol",
        "Arkana",
        "Laguna",
        "Dokker",
        "Clio",
        "Latitude",
        "19",
        "21",
        "Espace",
        "Vel Satis",
        "Modus",
        "Trafic",
        "Talisman",
        "Safrane",
        "Twingo",
        "6",
        "Megane RS",
        "Kadjar",
        "Clio RS",
        "20",
        "5",
        "Fregate",
        "25",
        "Avantime",
        "11",
        "Fuego",
        "Captur",
    ],
    "Renault Samsung": ["QM5", "SM3"],
    "Rolls-Royce": [
        "Wraith",
        "Dawn",
        "Ghost",
        "Phantom",
        "Silver Wraith",
        "Silver Seraph",
        "Cullinan",
        "Corniche",
        "20/25",
    ],
    "Rover": ["75", "200", "600", "800", "400", "45", "25", "Streetwise"],
    "SEAT": [
        "Altea",
        "Alhambra",
        "Toledo",
        "Leon",
        "Cordoba",
        "Ibiza",
        "Arosa",
        "Inca",
        "Leon Cupra",
        "Mii",
    ],
    "Saab": ["900", "9000", "9-3", "9-5", "9-7X", "9-4X", "96", "9-2X"],
    "Saturn": ["SL", "VUE", "SW", "Sky", "Aura", "SC", "Outlook"],
    "Scion": ["xA", "tC", "xB", "iA", "FR-S"],
    "Shanghai Maple": ["C31", "C61", "C51", "C32", "C81"],
    "ShuangHuan": ["Sceo"],
    "Simca": ["1307"],
    "Skoda": [
        "Octavia",
        "Superb",
        "Rapid",
        "Yeti",
        "Kodiaq",
        "Karoq",
        "Fabia",
        "Felicia",
        "Roomster",
        "Octavia RS",
        "Fabia RS",
        "105, 120",
        "Favorit",
        "Forman",
        "1200",
    ],
    "Smart": ["Fortwo", "Roadster", "Forfour"],
    "SsangYong": [
        "Actyon",
        "Rexton",
        "Kyron",
        "Istana",
        "Actyon Sports",
        "Korando Family",
        "Korando",
        "Musso",
        "Rodius",
        "Korando Sports",
        "Tivoli",
        "Stavic",
        "Korando Turismo",
    ],
    "Subaru": [
        "Legacy Lancaster",
        "Legacy",
        "Forester",
        "XV",
        "Outback",
        "Tribeca",
        "Impreza",
        "WRX STi",
        "Ascent",
        "Impreza WRX STi",
        "R2",
        "Leone",
        "Impreza WRX",
        "WRX",
        "Domingo",
        "Stella",
        "Exiga",
        "Traviq",
        "BRZ",
        "Trezia",
        "Sambar",
        "Pleo",
        "Rex",
        "Justy",
        "Dex",
        "Vivio",
        "Alcyone",
        "Pleo Plus",
        "Levorg",
        "Libero",
        "SVX",
    ],
    "Suzuki": [
        "Kizashi",
        "Grand Vitara",
        "SX4",
        "Solio",
        "Baleno",
        "Ignis",
        "Escudo",
        "Liana",
        "Jimny",
        "Hustler",
        "Swift",
        "Alto",
        "Wagon R+",
        "Cultus",
        "Aerio",
        "Vitara",
        "Sidekick",
        "Kei",
        "Samurai",
        "Wagon R",
        "MR Wagon",
        "Splash",
        "Forenza",
        "Esteem",
        "Landy",
        "Every",
        "X-90",
        "Carry",
        "Spacia",
        "Cervo",
        "Palette",
        "XL7",
        "Verona",
        "Cappuccino",
    ],
    "TATA": ["Indica", "Telcoline", "Xenon", "Estate"],
    "Tatra": ["T613"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y"],
    "Tianma": ["Century"],
    "Tianye": ["Admiral"],
    "Toyota": [
        "Vitz",
        "Avensis",
        "RAV4",
        "Prius",
        "Highlander",
        "Probox",
        "Carina",
        "Vellfire",
        "Sprinter Carib",
        "Prius v (+)",
        "Crown",
        "Land Cruiser",
        "Ipsum",
        "Carina E",
        "Raum",
        "Camry",
        "Land Cruiser Prado",
        "Estima",
        "Corolla",
        "Harrier",
        "Chaser",
        "Platz",
        "FunCargo",
        "Corolla Verso",
        "Cami",
        "Avensis Verso",
        "Caldina",
        "Vista",
        "Auris",
        "ISis",
        "Corolla Spacio",
        "Alphard",
        "C-HR",
        "Venza",
        "Hilux",
        "Premio",
        "Passo",
        "Mark II",
        "Corona",
        "Succeed",
        "Corona EXiV",
        "Sprinter Marino",
        "Wish",
        "Pronard",
        "Grand HiAce",
        "Sprinter",
        "Ractis",
        "Hilux Surf",
        "Granvia",
        "Town Ace",
        "Corsa",
        "Allion",
        "Tundra",
        "Cresta",
        "Sienna",
        "Rush",
        "Corolla Levin",
        "Sienta",
        "Yaris",
        "Mark X",
        "Sprinter Trueno",
        "Echo",
        "Carina ED",
        "Lite Ace",
        "Nadia",
        "Aqua",
        "Ist",
        "Duet",
        "Tank",
        "HiAce",
        "Belta",
        "Allex",
        "WiLL",
        "4Runner",
        "RegiusAce",
        "MR-S",
        "Spade",
        "Voxy",
        "Curren",
        "Noah",
        "Windom",
        "Prius Alpha",
        "Verso",
        "Celica",
        "Starlet",
        "Tercel",
        "Porte",
        "Brevis",
        "Sequoia",
        "Regius",
        "Altezza",
        "Kluger",
        "Crown Majesta",
        "bB",
        "Opa",
        "Celsior",
        "Picnic",
        "FJ Cruiser",
        "Mirai",
        "Tacoma",
        "Cavalier",
        "WiLL Cypha",
        "Esquire",
        "Aristo",
        "Passo Sette",
        "Fortuner",
        "Gaia",
        "GT86",
        "Cynos",
        "Soluna",
        "Matrix",
        "Verossa",
        "iQ",
        "Comfort",
        "Progres",
        "Corolla II",
        "Soarer",
        "Avalon",
        "Touring HiAce",
        "Scepter",
        "Prius c",
        "Corolla Rumion",
        "Sai",
        "Supra",
        "Camry Solara",
        "Previa",
        "Avanza",
        "Roomy",
        "Aygo",
        "Mark X ZiO",
        "Sparky",
        "Voltz",
        "MasterAce Surf",
        "Vanguard",
        "Blade",
        "Yaris Verso",
        "MR2",
        "Pixis Space",
        "Pixis Epoch",
        "Sera",
        "Paseo",
        "Pixis Van",
        "Verso-S",
        "Century",
        "Urban Cruiser",
        "Blizzard",
        "Vios",
        "Mega Cruiser",
        "Cressida",
        "COMS",
        "ProAce",
    ],
    "Trabant": ["P 601"],
    "Tramontana": ["Tramontana"],
    "Triumph": ["Spitfire", "TR4", "Acclaim"],
    "Vauxhall": ["Viva"],
    "Volkswagen": [
        "Transporter",
        "Golf",
        "Polo",
        "Touareg",
        "Sharan",
        "Passat",
        "Vento",
        "Golf Plus",
        "Tiguan",
        "Jetta",
        "Passat CC",
        "Phaeton",
        "Multivan",
        "Beetle",
        "Pointer",
        "Teramont",
        "Caddy",
        "Caravelle",
        "Bora",
        "Amarok",
        "Touran",
        "Routan",
        "Golf R",
        "Corrado",
        "Scirocco",
        "Lupo",
        "Polo GTI",
        "Taro",
        "Golf GTI",
        "Eos",
        "Karmann-Ghia",
        "Arteon",
        "Type 2",
        "K70",
        "Type 1",
        "EuroVan",
        "Santana",
        "Golf R32",
        "Type 3",
        "California",
        "Fox",
        "Iltis",
        "Passat (North America)",
        "Golf Country",
        "up!",
        "Lavida",
        "Type 166",
    ],
    "Volvo": [
        "XC90",
        "S80",
        "S40",
        "S60",
        "XC70",
        "V40",
        "XC60",
        "V90",
        "V60 Cross Country",
        "240 Series",
        "V50",
        "960",
        "V70",
        "V40 Cross Country",
        "460",
        "C30",
        "940",
        "740",
        "V90 Cross Country",
        "XC40",
        "S90",
        "S60 Cross Country",
        "850",
        "S70",
        "V60",
        "440",
        "C70",
        "760",
        "300 Series",
    ],
    "Vortex": ["Estina", "Tingo", "Corda"],
    "Wanderer": ["W50", "W23"],
    "Wartburg": ["1.3", "353"],
    "Willys": ["MB", "Jeepster"],
    "Xin Kai": ["Pickup X3", "SUV X3"],
    "Xpeng": ["G3", "P7"],
    "Yulon": ["Feeling"],
    "ZX": ["Grand Tiger", "Admiral", "Landmark"],
    "Zotye": ["T600", "Coupa"],
    "Автокам": ["2160"],
    "ГАЗ": [
        "21 «Волга»",
        "69",
        "24 «Волга»",
        "3110 «Волга»",
        "31105 «Волга»",
        "31029 «Волга»",
        "3102 «Волга»",
        "Volga Siber",
        "М-20 «Победа»",
        "14 «Чайка»",
        "ГАЗ 67",
        "12 ЗИМ",
        "310221 «Волга»",
        "3111 «Волга»",
        "А",
        "22 «Волга»",
        "М1",
        "2330 «Тигр»",
        "13 «Чайка»",
        "64",
        "М-72",
        "2308 «Атаман»",
        "46",
    ],
    "Гоночный автомобиль": ["Драгстер", "Формула", "Хот-род и Кастом"],
    "ЗАЗ": [
        "Chance",
        "Lanos",
        "1103 «Славута»",
        "Sens",
        "968",
        "965",
        "1102 «Таврия»",
        "Vida",
        "Forza",
        "1105 «Дана»",
        "966",
    ],
    "ЗИЛ": ["4104", "114"],
    "ЗиС": ["101", "110"],
    "ИЖ": ["2126 «Ода»", "21261 «Фабула»", "Москвич-412", "2125 «Комби»", "2717"],
    "Канонир": ["2317"],
    "ЛуАЗ": ["969", "967", "1302 Волынь"],
    "Москвич": [
        "407",
        "402",
        "2141",
        "412",
        "400",
        "2140",
        "Святогор",
        "408",
        "401",
        "411",
        "423",
        "403",
        "2138",
        "2137",
        "434П",
        "410",
        "430",
        "Иван Калита",
        "426",
        "Дуэт",
        "Князь Владимир",
        "2142",
        "2136",
    ],
    "СМЗ": ["С-3Д", "С-3А"],
    "ТагАЗ": ["Road Partner", "Tager", "C10", "Aquila", "Vega", "C190", "C-30"],
    "УАЗ": [
        "Hunter",
        "469",
        "Pickup",
        "Patriot",
        "3151",
        "3162 Simbir",
        "3153",
        "3160",
        "3159",
    ],
}
BODY_TYPE_OPTIONS = [
    "Хэтчбек 5 дв.",
    "Седан",
    "Внедорожник 5 дв.",
    "Универсал 5 дв.",
    "Фургон",
    "Лифтбек",
    "Минивэн",
    "Компактвэн",
    "Хэтчбек 3 дв.",
    "Внедорожник 3 дв.",
    "Купе",
    "Родстер",
    "Пикап двойная кабина",
    "Микровэн",
    "Внедорожник открытый",
    "Седан 2 дв.",
    "Седан-хардтоп",
    "Купе-хардтоп",
    "Фастбек",
    "Кабриолет",
    "Пикап полуторная кабина",
    "Пикап одинарная кабина",
    "Хэтчбек 4 дв.",
    "Фаэтон",
    "Лимузин",
    "Тарга",
    "Спидстер",
    "Универсал 3 дв.",
]
COLOR_OPTIONS = [
    "Серый",
    "Бежевый",
    "Синий",
    "Чёрный",
    "Красный",
    "Зелёный",
    "Белый",
    "Серебристый",
    "Коричневый",
    "Голубой",
    "Пурпурный",
    "Фиолетовый",
    "Жёлтый",
    "Золотистый",
    "Оранжевый",
    "Розовый",
]
FUEL_TYPE_OPTIONS = [
    "Электро",
    "Бензин",
    "Бензин, газобаллонное оборудование",
    "Дизель",
    "Дизель, газобаллонное оборудование",
    "Гибрид",
    "Гибрид, газобаллонное оборудование",
    "Газ",
    "Газ, газобаллонное оборудование",
]
TRANSMISSION_OPTIONS = [
    "Автоматическая",
    "Механическая",
    "Вариатор",
    "Роботизированная",
]
PTS_TYPE_OPTIONS = ["Оригинал", "Дубликат"]

DRIVE_OPTIONS = ["Задний", "Полный", "Передний"]
WHEEL_OPTIONS = ["Левый", "Правый"]
